version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: pg
    environment:
      POSTGRES_DB: satu_atap
      POSTGRES_USER: backend_kelompok1
      POSTGRES_PASSWORD: NaciNapIEulIONdLocKeNTArEvEGaeaD
    ports:
      - "15432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  memory_db:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "16379:6379"
volumes:
  pg_data:
